### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by ramszaenkar** [hermanTenuki/ASCII-Generator.site#104]
I have loved using the generator but it seems like for the last two days the site is down?

**Comment by hermanTenuki** [comment]
Hi, yes, im sorry. Once this political situation and sanctions toward russia began, i started to have big technical problems with server's mainteance/payments. For now it's fully taken down.

I've been seeing that many peoples used it daily, so on weekends i will be trying to buy and configure whole new server and host website on it. I will leave another comment if it's finally available.

For now, you can try to host website locally using [Fast local setup](https://github.com/hermanTenuki/ASCII-Generator.site#fast-local-setup) guide.

**Comment by hermanTenuki** [comment]
should be working now
